services:
  retodo:
    container_name: retodo
    build: .
    ports:
      - "${PORT:-8080}:80"
    volumes:
      - data:/data
    restart: unless-stopped

  sqlitebrowser:
    image: lscr.io/linuxserver/sqlitebrowser:latest
    container_name: sqlitebrowser
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - sqlitebrowser:/config
      - data:/retodo_data
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped

volumes:
  data:
  sqlitebrowser:
